Improved README.md
Claviz/xlstream pull request #28
Opened 2020-10-01 06:29 UTC by jacktherock

2020-10-01 06:35 UTC, jansivans requested changes

2020-10-01 06:35 UTC, jansivans commented on README.md
> +## xlstream
I would like this to stay a first level heading.

2020-10-01 06:44 UTC, merged

2020-10-01 06:45 UTC, jansivans commented
Thanks!

2020-10-01 06:46 UTC, jacktherock commented
> Thanks!



> Thanks!

> Here we go. Thank you for your suggestion .

2020-10-07 03:59 UTC, jacktherock commented
Hello can you do me a fever, please add hacktoberfest topic to this repo and label my file as _hacktoberfest accepted_ and check [hacktoberfest](https://hacktoberfest.digitalocean.com/hacktoberfest-update) for more info. Thank you!

2020-10-07 04:17 UTC, jansivans commented
Yeah sure I can do this, but only if you will make some valuable PR. For example, you can cover uncovered lines with tests. 

As Hacktoberfest says:

_Participating in Hacktoberfest leads to personal growth, professional opportunities, and community building. However, it all begins with meaningful contributions to open source software._

Editing few lines in README isn't a meaningful contribution and doesn't lead you to personal growth.

2020-10-07 08:29 UTC, jacktherock commented
Then what should I do next? Can you suggest.

2020-10-07 08:31 UTC, jansivans commented
Please read my response more carefully - you can cover uncovered lines with tests.